'use client';

import React, { useState } from 'react';
import { useLayerOS } from '@/lib/store';
import { useI18n } from '@/lib/i18n/context';
import { formatIndianCurrency, formatIndianNumber } from '@/lib/calc';
import {
  FileSpreadsheet,
  Share2,
  Download,
  Printer,
  Calendar,
  Sparkles,
  Egg,
  Wheat,
  CheckCircle,
} from 'lucide-react';

export function ReportsModule() {
  const { farm, flock, todayRecord, dailyRecords, customers } = useLayerOS();
  const { t } = useI18n();

  const [reportType, setReportType] = useState<'daily-card' | 'monthly-mis' | 'outstanding'>('daily-card');

  const totalOutstanding = customers.reduce((sum, c) => sum + c.currentOutstanding, 0);

  // Formatted WhatsApp message for Farm Report Card
  const waReportMessage = encodeURIComponent(
`*📊 ${farm.name} - दैनिक पोल्ट्री अहवाल*
📅 दिनांक: ${todayRecord.recordDate}
🐣 बॅच: ${flock.batchCode} (${flock.ageWeeks} आठवडे)

🐔 जिवंत पक्षी: ${formatIndianNumber(todayRecord.closingBirds)}
🥚 गोळा झालेली अंडी: ${formatIndianNumber(todayRecord.totalEggsCollected)}
📈 उत्पादन (HD%): ${todayRecord.hdPct}% (मानक: ९१.५%)
🌾 वापरलेला खुराक: ${formatIndianNumber(todayRecord.feedIssuedKg)} kg (${todayRecord.feedPerBirdG} g/पक्षी)
💀 मृत्यू: ${todayRecord.mortality} पक्षी

💰 *आर्थिक सारांश:*
• आजचा विक्री दर: ₹${todayRecord.sellingPricePerEgg}/अंडी (₹${Math.round(todayRecord.sellingPricePerEgg * 100)}/१००)
• ब्रेक-इव्हन दर: ₹${todayRecord.breakEvenEggPrice}/अंडी
• एकूण विक्री महसूल: ₹${formatIndianNumber(Math.round(todayRecord.totalEggsCollected * todayRecord.sellingPricePerEgg))}
• थेट नफा (Cash): ₹${formatIndianNumber(todayRecord.simpleOperatingProfit)}
• खरा नफा (True Profit): ₹${formatIndianNumber(todayRecord.trueProfit)}

_Generated by LayerOS AI ERP_`
  );

  const handlePrint = () => {
    window.print();
  };

  const handleExportCSV = () => {
    const headers = "Date,ClosingBirds,EggsCollected,HDPct,FeedKg,FeedPerBirdG,Mortality,SellingRate,OperatingProfit,TrueProfit\n";
    const rows = dailyRecords.map(r => 
      `${r.recordDate},${r.closingBirds},${r.totalEggsCollected},${r.hdPct},${r.feedIssuedKg},${r.feedPerBirdG},${r.mortality},${r.sellingPricePerEgg},${r.simpleOperatingProfit},${r.trueProfit}`
    ).join("\n");
    const blob = new Blob([headers + rows], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute("download", `LayerOS_DailyRecords_${todayRecord.recordDate}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="card-layer p-5 border border-[#E7E2D6] dark:border-[#263B30] bg-white dark:bg-[#16241D]">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-4 border-b border-[#E7E2D6] dark:border-[#263B30] gap-3">
          <div>
            <h2 className="text-xl font-black text-[#0B1E15] dark:text-white flex items-center gap-2">
              <FileSpreadsheet className="w-6 h-6 text-[#1F4D3A] dark:text-[#3BA378]" />
              <span>अहवाल व शेअरिंग (Reports & Exports)</span>
            </h2>
            <p className="text-xs text-[#2D4538] dark:text-[#CBDCD4] font-semibold mt-1">
              दैनिक फार्म रिपोर्ट कार्ड, WhatsApp शेअर, PDF प्रिंट आणि Excel CSV डाऊनलोड
            </p>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleExportCSV}
              className="py-2 px-3 rounded-xl border border-[#E7E2D6] dark:border-[#263B30] text-xs font-bold text-[#0B1E15] dark:text-white flex items-center gap-1.5 hover:bg-gray-50 dark:hover:bg-[#1F3027]"
            >
              <Download className="w-4 h-4 text-[#1F4D3A] dark:text-[#3BA378]" />
              <span>Excel (CSV)</span>
            </button>
            <button
              onClick={handlePrint}
              className="py-2 px-3 rounded-xl bg-[#1F4D3A] hover:bg-[#173A2C] text-white text-xs font-bold flex items-center gap-1.5 shadow-sm"
            >
              <Printer className="w-4 h-4" />
              <span>PDF प्रिंट करा</span>
            </button>
          </div>
        </div>

        {/* Tab Buttons */}
        <div className="flex items-center gap-2 mt-4 overflow-x-auto pb-1">
          <button
            onClick={() => setReportType('daily-card')}
            className={`px-4 py-2 rounded-xl text-xs font-bold transition-all whitespace-nowrap ${
              reportType === 'daily-card'
                ? 'bg-[#1F4D3A] text-white shadow-sm'
                : 'bg-[#FAF8F3] dark:bg-[#1F3027] text-[#2D4538] dark:text-[#CBDCD4] hover:text-[#0B1E15] font-bold'
            }`}
          >
            दैनिक रिपोर्ट कार्ड (Daily Card)
          </button>
          <button
            onClick={() => setReportType('monthly-mis')}
            className={`px-4 py-2 rounded-xl text-xs font-bold transition-all whitespace-nowrap ${
              reportType === 'monthly-mis'
                ? 'bg-[#1F4D3A] text-white shadow-sm'
                : 'bg-[#FAF8F3] dark:bg-[#1F3027] text-[#2D4538] dark:text-[#CBDCD4] hover:text-[#0B1E15] font-bold'
            }`}
          >
            मासिक एमआयएस सारांश (Monthly MIS)
          </button>
          <button
            onClick={() => setReportType('outstanding')}
            className={`px-4 py-2 rounded-xl text-xs font-bold transition-all whitespace-nowrap ${
              reportType === 'outstanding'
                ? 'bg-[#1F4D3A] text-white shadow-sm'
                : 'bg-[#FAF8F3] dark:bg-[#1F3027] text-[#2D4538] dark:text-[#CBDCD4] hover:text-[#0B1E15] font-bold'
            }`}
          >
            थकबाकी अहवाल (Customer Ledgers)
          </button>
        </div>
      </div>

      {/* 1. DAILY REPORT CARD TAB */}
      {reportType === 'daily-card' && (
        <div className="card-layer p-6 md:p-8 border-2 border-[#1F4D3A]/20 bg-white dark:bg-[#16241D] max-w-2xl mx-auto shadow-xl space-y-6">
          {/* Card Top Brand */}
          <div className="text-center pb-4 border-b border-[#E7E2D6] dark:border-[#263B30]">
            <div className="w-12 h-12 mx-auto rounded-xl bg-[#1F4D3A] text-white flex items-center justify-center font-bold text-xl mb-2">
              🥚
            </div>
            <h3 className="text-lg font-black text-[#0B1E15] dark:text-white">
              {farm.name}
            </h3>
            <p className="text-xs text-[#2D4538] dark:text-[#CBDCD4] font-semibold mt-0.5">
              दैनिक उत्पादन व आर्थिक कामगिरी अहवाल • {todayRecord.recordDate}
            </p>
          </div>

          {/* Operational Metrics */}
          <div className="grid grid-cols-2 gap-3 text-xs">
            <div className="p-3 rounded-xl bg-[#FAF8F3] dark:bg-[#1F3027] border border-[#E7E2D6] dark:border-[#263B30]">
              <div className="text-[#2D4538] dark:text-[#CBDCD4] font-bold">जिवंत पक्षी</div>
              <div className="text-base font-black text-[#0B1E15] dark:text-white mt-0.5">
                {formatIndianNumber(todayRecord.closingBirds)}
              </div>
            </div>
            <div className="p-3 rounded-xl bg-[#FAF8F3] dark:bg-[#1F3027] border border-[#E7E2D6] dark:border-[#263B30]">
              <div className="text-[#2D4538] dark:text-[#CBDCD4] font-bold">गोळा झालेली अंडी</div>
              <div className="text-base font-black text-[#1F4D3A] dark:text-[#3BA378] mt-0.5">
                {formatIndianNumber(todayRecord.totalEggsCollected)}
              </div>
            </div>
            <div className="p-3 rounded-xl bg-[#FAF8F3] dark:bg-[#1F3027] border border-[#E7E2D6] dark:border-[#263B30]">
              <div className="text-[#2D4538] dark:text-[#CBDCD4] font-bold">उत्पादन (HD%)</div>
              <div className="text-base font-black text-[#1F4D3A] dark:text-[#3BA378] mt-0.5">
                {todayRecord.hdPct}%
              </div>
            </div>
            <div className="p-3 rounded-xl bg-[#FAF8F3] dark:bg-[#1F3027] border border-[#E7E2D6] dark:border-[#263B30]">
              <div className="text-[#2D4538] dark:text-[#CBDCD4] font-bold">प्रति पक्षी खुराक</div>
              <div className="text-base font-black text-[#0B1E15] dark:text-white mt-0.5">
                {todayRecord.feedPerBirdG} ग्रॅम
              </div>
            </div>
          </div>

          {/* Financial Breakdown */}
          <div className="p-4 rounded-2xl bg-[#EAF3EF] dark:bg-[#182B22] border border-[#2D6B52]/30 space-y-2 text-xs">
            <div className="flex justify-between font-bold text-[#0B1E15] dark:text-white">
              <span>अंडी विक्री महसूल:</span>
              <span className="font-black">{formatIndianCurrency(todayRecord.totalEggsCollected * todayRecord.sellingPricePerEgg)}</span>
            </div>
            <div className="flex justify-between font-semibold text-red-600">
              <span>एकूण रोख खर्च:</span>
              <span className="font-bold">-{formatIndianCurrency(127500)}</span>
            </div>
            <div className="flex justify-between font-black text-sm pt-2 border-t border-emerald-200 dark:border-emerald-800 text-emerald-900 dark:text-emerald-300">
              <span>थेट रोख नफा (Operating Profit):</span>
              <span>{formatIndianCurrency(todayRecord.simpleOperatingProfit)}</span>
            </div>
            <div className="flex justify-between font-black text-sm text-[#D9A441]">
              <span>सर्व घसाऱ्यांनंतर खरा नफा (True Profit):</span>
              <span>{formatIndianCurrency(todayRecord.trueProfit)}</span>
            </div>
          </div>

          {/* WhatsApp Share Button */}
          <div className="pt-2">
            <a
              href={`https://wa.me/?text=${waReportMessage}`}
              target="_blank"
              rel="noopener noreferrer"
              className="w-full py-3.5 px-4 rounded-xl bg-[#25D366] hover:bg-[#20BD5A] text-white font-black text-sm flex items-center justify-center gap-2 shadow-md"
            >
              <Share2 className="w-5 h-5" />
              <span>WhatsApp वर दैनिक अहवाल पाठवा</span>
            </a>
          </div>
        </div>
      )}

      {/* 2. MONTHLY MIS TAB */}
      {reportType === 'monthly-mis' && (
        <div className="card-layer p-5 border border-[#E7E2D6] dark:border-[#263B30] bg-white dark:bg-[#16241D] space-y-4">
          <div className="pb-3 border-b border-[#E7E2D6] dark:border-[#263B30]">
            <h3 className="text-sm font-black text-[#0B1E15] dark:text-white">
              मासिक एमआयएस सारांश (Monthly MIS Table)
            </h3>
            <p className="text-xs text-[#2D4538] dark:text-[#CBDCD4] font-medium mt-0.5">
              मागील ३० दिवसांची दैनिक कामगिरी व वित्तीय सारांश
            </p>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-xs text-left">
              <thead className="bg-[#FAF8F3] dark:bg-[#1F3027] text-[#0B1E15] dark:text-white font-bold uppercase text-[10px]">
                <tr>
                  <th className="p-3">दिनांक</th>
                  <th className="p-3">अंडी संकलन</th>
                  <th className="p-3">HD%</th>
                  <th className="p-3">खुराक (kg)</th>
                  <th className="p-3">मृत्यू</th>
                  <th className="p-3">विक्री दर</th>
                  <th className="p-3">थेट नफा</th>
                  <th className="p-3 text-right">खरा नफा</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100 dark:divide-gray-800 text-[#0B1E15] dark:text-white">
                {dailyRecords.slice(-15).reverse().map(r => (
                  <tr key={r.id} className="hover:bg-gray-50/50 dark:hover:bg-[#1F3027]/50">
                    <td className="p-3 font-bold">{r.recordDate}</td>
                    <td className="p-3 font-semibold">{formatIndianNumber(r.totalEggsCollected)}</td>
                    <td className="p-3 font-black text-[#1F4D3A] dark:text-[#3BA378]">{r.hdPct}%</td>
                    <td className="p-3 font-medium">{formatIndianNumber(r.feedIssuedKg)}</td>
                    <td className="p-3 text-red-600 font-black">{r.mortality}</td>
                    <td className="p-3 font-bold text-[#D9A441]">₹{r.sellingPricePerEgg}</td>
                    <td className="p-3 font-bold text-emerald-600">{formatIndianCurrency(r.simpleOperatingProfit)}</td>
                    <td className="p-3 font-black text-right text-amber-600">{formatIndianCurrency(r.trueProfit)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* 3. OUTSTANDING TAB */}
      {reportType === 'outstanding' && (
        <div className="card-layer p-5 border border-[#E7E2D6] dark:border-[#263B30] bg-white dark:bg-[#16241D] space-y-4">
          <div className="flex items-center justify-between pb-3 border-b border-[#E7E2D6] dark:border-[#263B30]">
            <div>
              <h3 className="text-sm font-black text-[#0B1E15] dark:text-white">
                ग्राहकांची थकबाकी यादी (Receivables Ledger)
              </h3>
              <p className="text-xs text-[#2D4538] dark:text-[#CBDCD4] font-semibold mt-0.5">
                एकूण उधारी: <strong className="text-red-600 font-black">{formatIndianCurrency(totalOutstanding)}</strong>
              </p>
            </div>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-xs text-left">
              <thead className="bg-[#FAF8F3] dark:bg-[#1F3027] text-[#0B1E15] dark:text-white font-bold uppercase text-[10px]">
                <tr>
                  <th className="p-3">ग्राहक</th>
                  <th className="p-3">परिसर</th>
                  <th className="p-3">क्रेडिट मुदत</th>
                  <th className="p-3">सरासरी भरणा दिवस</th>
                  <th className="p-3 text-right">चालू बाकी</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100 dark:divide-gray-800 text-[#0B1E15] dark:text-white">
                {customers.map(c => (
                  <tr key={c.id}>
                    <td className="p-3 font-bold">{c.name}</td>
                    <td className="p-3 text-[#2D4538] dark:text-[#CBDCD4] font-medium">{c.area}</td>
                    <td className="p-3 font-medium">{c.creditDays} दिवस</td>
                    <td className="p-3 font-semibold text-emerald-600">{c.averageDaysToPay} दिवस</td>
                    <td className="p-3 font-black text-right text-amber-700 dark:text-amber-400">
                      {formatIndianCurrency(c.currentOutstanding)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
